name: Daily PvP Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
      BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp requests

      - name: Debug Show full directory and files
        run: |
          echo "Working directory: $(pwd)"
          ls -R

      - name: Run PvP Sync Script
        run: python sync_pvp.py

      - name: Commit results to dev
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add achiev/region_*.x
          git commit -m "Daily PvP sync update" || echo "No changes to commit"
          git push origin dev
